In [1]:
# 1. load library
import pandas as pd 

# 2. Load datasets
# read the file 
df = pd.read_csv(r"D:\Nassu Project\Nassau_Candy_Distributor.csv")
# give the 5 rows as a output
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
# 3. check Shape
# No. of rows and columns
df.shape

(10194, 18)

In [ ]:
# 4. chech inforamtion/data types
# details of the columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 1.4 MB

In [ ]:
# 5. Check missing values
# Give the sum of null values in each row
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [ ]:
# 6. check the duplicates
# Checks the duplicate rows
df.duplicated().sum()

np.int64(0)

In [ ]:
# 7. Statistical summery
# Looks at each numerical column
df.describe()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,134468.961154,13.908537,3.791838,9.166451,4.742087
std,2942.898656,20231.483007,11.341020,2.228317,6.643740,5.061647
min,1.000000,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,192314.000000,260.000000,14.000000,130.000000,130.000000

In [ ]:
# Inspect Catogirical fields
print(df["Ship Mode"].unique())
print(df["Region"].unique())

<StringArray>
['Standard Class', 'First Class', 'Second Class', 'Same Day']
Length: 4, dtype: str
<StringArray>
['Interior', 'Atlantic', 'Gulf', 'Pacific']
Length: 4, dtype: str

In [34]:
print(df["Country/Region"].unique())
print(df["City"].unique())

<StringArray>
['United States', 'Canada']
Length: 2, dtype: str
<StringArray>
[     'Houston',   'Naperville', 'Philadelphia',    'Henderson',
       'Athens',  'Los Angeles',   'Huntsville',       'Laredo',
  'Springfield',        'Dover',
 ...
      'Ontario',       'Renton',       'Canton',  'Summerville',
    'Gladstone',     'Whittier',      'Abilene',     'Palatine',
  'Port Orange',      'Danbury']
Length: 542, dtype: str

In [35]:
print(df["State/Province"].unique())
print(df["Division"].unique())

<StringArray>
[                    'Texas',                  'Illinois',
              'Pennsylvania',                  'Kentucky',
                   'Georgia',                'California',
                  'Virginia',                  'Delaware',
            'South Carolina',                      'Ohio',
                 'Louisiana',                    'Oregon',
                   'Arizona',                  'Arkansas',
                  'Michigan',                 'Tennessee',
                   'Florida',                   'Ontario',
                   'Indiana',                    'Nevada',
              'South Dakota',                  'New York',
                 'Wisconsin',                'Washington',
                'New Jersey',                  'Missouri',
            'North Carolina',                  'Colorado',
                   'Alberta',                      'Utah',
                 'Minnesota',               'Mississippi',
                      'Iowa',                'New Mexico',
             'Massachusetts',                   'Alabama',
                     'Idaho',                   'Montana',
                  'Maryland',               'Connecticut',
             'New Hampshire',          'British Columbia',
                    'Quebec',               'Nova Scotia',
                  'Oklahoma',                  'Nebraska',
                     'Maine',                    'Kansas',
              'Rhode Island', 'Newfoundland and Labrador',
             'New Brunswick',      'Prince Edward Island',
      'District of Columbia',                   'Vermont',
                  'Manitoba',              'Saskatchewan',
                   'Wyoming',              'North Dakota',
             'West Virginia']
Length: 59, dtype: str
<StringArray>
['Chocolate', 'Other', 'Sugar']
Length: 3, dtype: str