In [17]:
import pandas as pd 


# read the file 
df_cleaned = pd.read_csv(r"D:\Nassu Project\Nassau_Candy_Distributor.csv")
# give the 5 rows as a output
df_cleaned.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [18]:
df_cleaned.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [20]:
df_cleaned.duplicated().sum()

np.int64(0)

In [23]:
df_cleaned["Order Date"] = pd.to_datetime(
    df_cleaned["Order Date"],
    format="%d-%m-%Y"
)

df_cleaned["Ship Date"] = pd.to_datetime(
    df_cleaned["Ship Date"],
    format="%d-%m-%Y"
)

In [24]:
df_cleaned[df_cleaned["Ship Date"]<df_cleaned["Order Date"]]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Country/Region, City, State/Province, Postal Code, Division, Region, Product ID, Product Name, Sales, Units, Gross Profit, Cost]
Index: []

In [25]:
df_cleaned[["Sales", "Units", "Gross Profit", "Cost"]].describe()

              Sales         Units  Gross Profit          Cost
count  10194.000000  10194.000000  10194.000000  10194.000000
mean      13.908537      3.791838      9.166451      4.742087
std       11.341020      2.228317      6.643740      5.061647
min        1.250000      1.000000      0.250000      0.600000
25%        7.200000      2.000000      4.900000      2.400000
50%       10.800000      3.000000      7.470000      3.600000
75%       18.000000      5.000000     12.250000      5.700000
max      260.000000     14.000000    130.000000    130.000000

In [26]:
df_cleaned["Region"].value_counts()

Region
Pacific     3253
Atlantic    2986
Interior    2335
Gulf        1620
Name: count, dtype: int64

In [27]:
df_cleaned["State/Province"].value_counts()

State/Province
California                   2001
New York                     1128
Texas                         985
Pennsylvania                  587
Washington                    506
Illinois                      492
Ohio                          469
Florida                       383
Michigan                      255
North Carolina                249
Virginia                      224
Arizona                       224
Georgia                       184
Tennessee                     183
Colorado                      182
Indiana                       149
Kentucky                      139
Massachusetts                 135
New Jersey                    130
Oregon                        124
Wisconsin                     110
Maryland                      105
Delaware                       96
Minnesota                      89
Connecticut                    82
Missouri                       66
Oklahoma                       66
Alabama                        61
Arkansas                       60
Ontario                        58
Rhode Island                   56
Utah                           53
Mississippi                    53
Quebec                         50
South Carolina                 42
Louisiana                      42
Nevada                         39
Nebraska                       38
New Mexico                     37
Iowa                           30
New Hampshire                  27
Alberta                        26
Kansas                         24
British Columbia               22
Idaho                          21
Montana                        15
South Dakota                   12
Manitoba                       12
Vermont                        11
Prince Edward Island           10
District of Columbia           10
Maine                           8
New Brunswick                   8
North Dakota                    7
Nova Scotia                     6
Newfoundland and Labrador       6
West Virginia                   4
Saskatchewan                    2
Wyoming                         1
Name: count, dtype: int64