In [2]:
import pandas as pd

df_features = pd.read_csv(
    r"D:\Nassu Project\Nassau-Candy-Shipping-Analysis\data\processed\factory_mapped_data.csv"
)

In [3]:
df_features.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Factory
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,Wicked Choccy's
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,Wicked Choccy's
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,Lot's O' Nuts
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,Lot's O' Nuts
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,Wicked Choccy's

In [4]:
# oandas read the dates as a string so when we have imported the csv file date is treated as a stirng. so, we are 
# using following program to convert it into actual date and time.

df_features["Order Date"] = pd.to_datetime(
    df_features["Order Date"], format="%d-%m-%Y"
)

df_features["Ship Date"] = pd.to_datetime(
    df_features["Ship Date"], format="%d-%m-%Y"
)

In [ ]:
# Calculating shipping lead time and storing it into the column
df_features["Shipping Lead Time"] = (df_features["Ship Date"] - df_features["Order Date"]).dt.days

In [6]:
df_features[["Order Date", "Ship Date", "Shipping Lead Time"]].head(10)

  Order Date  Ship Date  Shipping Lead Time
0 2024-01-03 2026-06-30                 909
1 2024-01-04 2026-07-01                 909
2 2024-01-04 2026-07-01                 909
3 2024-01-04 2026-07-01                 909
4 2024-01-05 2026-07-05                 912
5 2024-01-06 2026-07-03                 909
6 2024-01-06 2026-07-03                 909
7 2024-01-06 2026-06-30                 906
8 2024-01-06 2026-07-03                 909
9 2024-01-06 2026-07-03                 909

In [7]:
df_features["Shipping Lead Time"].describe()

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Shipping Lead Time, dtype: float64

In [9]:
df_features["Shipping Lead Time"].value_counts().head(10)

Shipping Lead Time
1273    1326
1274    1035
1639     896
1640     657
1275     612
1271     610
908      591
909      519
1272     456
1637     449
Name: count, dtype: int64

In [10]:
df_features[["Order Date", "Ship Date"]].tail(10)

      Order Date  Ship Date
10184 2025-12-29 2030-06-25
10185 2025-12-29 2030-06-25
10186 2025-12-30 2030-06-26
10187 2025-12-30 2030-06-28
10188 2025-12-30 2030-06-26
10189 2025-12-30 2030-06-26
10190 2025-12-30 2030-06-26
10191 2025-12-30 2030-06-26
10192 2025-12-30 2030-06-26
10193 2025-12-30 2030-06-26

In [11]:
# Creating a factory customer state route
df_features["Route"] = (
    df_features["Factory"] + " → " + df_features["State/Province"]
)

In [12]:
df_features[["Factory", "State/Province", "Route"]].head(10)

           Factory State/Province                           Route
0  Wicked Choccy's          Texas         Wicked Choccy's → Texas
1  Wicked Choccy's       Illinois      Wicked Choccy's → Illinois
2    Lot's O' Nuts       Illinois        Lot's O' Nuts → Illinois
3    Lot's O' Nuts       Illinois        Lot's O' Nuts → Illinois
4  Wicked Choccy's   Pennsylvania  Wicked Choccy's → Pennsylvania
5    Lot's O' Nuts       Kentucky        Lot's O' Nuts → Kentucky
6  Wicked Choccy's       Kentucky      Wicked Choccy's → Kentucky
7  Wicked Choccy's        Georgia       Wicked Choccy's → Georgia
8    Lot's O' Nuts       Kentucky        Lot's O' Nuts → Kentucky
9  Wicked Choccy's       Kentucky      Wicked Choccy's → Kentucky

In [13]:
df_features["Region Route"] = (
    df_features["Factory"] + " → " + df_features["Region"]
)

In [14]:
df_features[["Factory", "Region", "Region Route"]].head(10)

           Factory    Region                Region Route
0  Wicked Choccy's  Interior  Wicked Choccy's → Interior
1  Wicked Choccy's  Interior  Wicked Choccy's → Interior
2    Lot's O' Nuts  Interior    Lot's O' Nuts → Interior
3    Lot's O' Nuts  Interior    Lot's O' Nuts → Interior
4  Wicked Choccy's  Atlantic  Wicked Choccy's → Atlantic
5    Lot's O' Nuts      Gulf        Lot's O' Nuts → Gulf
6  Wicked Choccy's      Gulf      Wicked Choccy's → Gulf
7  Wicked Choccy's      Gulf      Wicked Choccy's → Gulf
8    Lot's O' Nuts      Gulf        Lot's O' Nuts → Gulf
9  Wicked Choccy's      Gulf      Wicked Choccy's → Gulf

In [15]:
df_features["Ship Mode"].value_counts()

Ship Mode
Standard Class    6120
Second Class      1979
First Class       1548
Same Day           547
Name: count, dtype: int64

In [16]:
df_features.to_csv(
    r"D:\Nassu Project\Nassau-Candy-Shipping-Analysis\data\processed\feature_engineered_data.csv",
    index=False
)